export const translations = {
  RUS: {
    home: 'Главный',
    results: 'Результаты',
    profile: 'Профиль',
    library: 'Библиотека',
    search: 'Поиск тестов...',
    startTest: 'Начать тест',
    score: 'Баллы',
    class: 'Класс',
    name: 'Имя',
    download: 'Скачать',
    read: 'Читать',
    admin: 'Админ',
    noResults: 'Результатов пока нет',
    books: 'Электронные книги',
    student: 'Ученик',
    info: 'Инфо',
    studentInfo: 'Информация об ученике',
    fullName: 'ФИО',
    phone: 'Телефон',
    status: 'Статус',
    testsTaken: 'Сданные тесты',
    noTestsTaken: 'Вы еще не сдавали тесты',
    settings: 'Настройки',
    adminPanel: 'Админ панель',
    logout: 'Выход',
    save: 'Сохранить',
    changePassword: 'Сменить пароль',
    newPassword: 'Новый пароль',
    personalInfo: 'Личная информация',
    language: 'Язык',
    adminPanelTitle: 'Админ Панель',
    subjects: 'Предметы',
    analytics: 'Аналитика',
    studentsBase: 'База учеников',
    back: 'Назад',
    addSubject: 'Добавить предмет',
    addBook: 'Добавить книгу',
    editBook: 'Редактировать книгу',
    cancel: 'Отмена',
    uploadFile: 'Загрузить файл',
    bookName: 'Название книги',
    fileUrl: 'URL файла',
    searchSubjects: 'Поиск предметов...',
    searchResults: 'Поиск результатов...',
    published: 'Опубликовано',
    draft: 'Черновик',
    studentName: 'Имя ученика',
    date: 'Дата',
    changeRole: 'Сменить роль',
    loading: 'Загрузка...',
    testName: 'Название теста',
    category: 'Категория',
    description: 'Описание',
    timeMinutes: 'Время (мин)',
    imageUrl: 'URL изображения',
    questions: 'Вопросы',
    addQuestion: '+ Добавить вопрос',
    preview: 'Предпросмотр',
    questionText: 'Текст вопроса',
    option: 'Вариант',
    login: 'Войти',
    register: 'Регистрация',
    phone: 'Телефон',
    password: 'Пароль',
    noAccount: 'Нет аккаунта? Зарегистрируйтесь',
    haveAccount: 'Уже есть аккаунт? Войдите',
    authError: 'Неверный телефон или пароль',
    alreadyRegistered: 'Вы уже зарегистрированы. Пожалуйста, войдите.',
    executing: 'Выполняется...',
    testFinished: 'Тест завершен!',
    resultSaved: 'Ваш результат сохранен в системе.',
    backToHome: 'Вернуться на главную',
    question: 'Вопрос',
    of: 'из',
    finish: 'Завершить',
    next: 'Далее',
    previous: 'Назад',
    passwordChanged: 'Пароль успешно изменен'
  },
  TJ: {
    home: 'Асосӣ',
    results: 'Натиҷаҳо',
    profile: 'Профил',
    library: 'Китобхона',
    search: 'Ҷустуҷӯи тестҳо...',
    startTest: 'Оғози тест',
    score: 'Холҳо',
    class: 'Синф',
    name: 'Ном',
    download: 'Боргирӣ',
    read: 'Хондан',
    admin: 'Админ',
    noResults: 'Ҳанӯз натиҷаҳо нест',
    books: 'Китобҳои электронӣ',
    student: 'Хонанда',
    info: 'Инфо',
    studentInfo: 'Маълумоти хонанда',
    fullName: 'Ному Насаб',
    phone: 'Телефон',
    status: 'Статус',
    testsTaken: 'Фанҳои супоридашуда',
    noTestsTaken: 'Ҳанӯз тест насупоридаед',
    settings: 'Танзимот',
    adminPanel: 'Админ панел',
    logout: 'Баромад',
    save: 'Захира кардан',
    changePassword: 'Ивази рамз',
    newPassword: 'Рамзи нав',
    personalInfo: 'Маълумоти шахсӣ',
    language: 'Забон',
    adminPanelTitle: 'Админ Панел',
    subjects: 'Фанҳо',
    analytics: 'Аналитика',
    studentsBase: 'Базаи хонандагон',
    back: 'Баргаштан',
    addSubject: 'Иловаи фан',
    addBook: 'Иловаи китоб',
    editBook: 'Таҳрири китоб',
    cancel: 'Бекор кардан',
    uploadFile: 'Боргузории файл',
    bookName: 'Номи китоб',
    fileUrl: 'URL-и файл',
    searchSubjects: 'Ҷустуҷӯи фанҳо...',
    searchResults: 'Ҷустуҷӯи натиҷаҳо...',
    published: 'Нашр шуд',
    draft: 'Черновик',
    studentName: 'Номи хонанда',
    date: 'Сана',
    changeRole: 'Ивази нақш',
    loading: 'Дар ҳоли боргузорӣ...',
    testName: 'Номи тест',
    category: 'Категория',
    description: 'Тавсиф',
    timeMinutes: 'Вақт (дақиқа)',
    imageUrl: 'URL-и сурат',
    questions: 'Саволҳо',
    addQuestion: '+ Иловаи савол',
    preview: 'Пешнамоиш',
    questionText: 'Матни савол',
    option: 'Варианти',
    login: 'Воридшавӣ',
    register: 'Бақайдгирӣ',
    phone: 'Рақами телефон',
    password: 'Парол',
    noAccount: 'Ҳанӯз ҳисоб надоред? Сабти ном кунед',
    haveAccount: 'Аллакай ҳисоб доред? Ворид шавед',
    authError: 'Телефон ё парол нодуруст аст',
    alreadyRegistered: 'Шумо аллакай сабт шудаед. Лутфан ворид шавед.',
    executing: 'Дар ҳоли иҷро...',
    testFinished: 'Тест тамом шуд!',
    resultSaved: 'Натиҷаи шумо дар система сабт шуд.',
    backToHome: 'Баргаштан ба асосӣ',
    question: 'Савол',
    of: 'аз',
    finish: 'Тамом кардан',
    next: 'Баъдӣ',
    previous: 'Пештар',
    passwordChanged: 'Рамз бомуваффақият иваз шуд'
  },
  EN: {
    home: 'Home',
    results: 'Results',
    profile: 'Profile',
    library: 'Library',
    search: 'Search tests...',
    startTest: 'Start Test',
    score: 'Score',
    class: 'Class',
    name: 'Name',
    download: 'Download',
    read: 'Read',
    admin: 'Admin',
    noResults: 'No results yet',
    books: 'E-Books',
    student: 'Student',
    info: 'Info',
    studentInfo: 'Student Information',
    fullName: 'Full Name',
    phone: 'Phone',
    status: 'Status',
    testsTaken: 'Tests Taken',
    noTestsTaken: 'No tests taken yet',
    settings: 'Settings',
    adminPanel: 'Admin Panel',
    logout: 'Logout',
    save: 'Save',
    changePassword: 'Change Password',
    newPassword: 'New Password',
    personalInfo: 'Personal Information',
    language: 'Language',
    adminPanelTitle: 'Admin Panel',
    subjects: 'Subjects',
    analytics: 'Analytics',
    studentsBase: 'Students Database',
    back: 'Back',
    addSubject: 'Add Subject',
    addBook: 'Add Book',
    editBook: 'Edit Book',
    cancel: 'Cancel',
    uploadFile: 'Upload File',
    bookName: 'Book Name',
    fileUrl: 'File URL',
    searchSubjects: 'Search subjects...',
    searchResults: 'Search results...',
    published: 'Published',
    draft: 'Draft',
    studentName: 'Student Name',
    date: 'Date',
    changeRole: 'Change Role',
    loading: 'Loading...',
    testName: 'Test Name',
    category: 'Category',
    description: 'Description',
    timeMinutes: 'Time (min)',
    imageUrl: 'Image URL',
    questions: 'Questions',
    addQuestion: '+ Add Question',
    preview: 'Preview',
    questionText: 'Question Text',
    option: 'Option',
    login: 'Login',
    register: 'Register',
    phone: 'Phone Number',
    password: 'Password',
    noAccount: 'No account? Register',
    haveAccount: 'Already have an account? Login',
    authError: 'Invalid phone or password',
    alreadyRegistered: 'Already registered. Please login.',
    executing: 'Executing...',
    testFinished: 'Test finished!',
    resultSaved: 'Your result is saved in the system.',
    backToHome: 'Back to home',
    question: 'Question',
    of: 'of',
    finish: 'Finish',
    next: 'Next',
    previous: 'Previous',
    passwordChanged: 'Password changed successfully'
  }
};

export const MOCK_TESTS = [
  { id: '1', title: 'Алгебра: Квадратные уравнения', subject: 'Математика', questionsCount: 20, image: 'https://picsum.photos/seed/math/400/300', description: 'Тест на знание формул дискриминанта и корней.' },
  { id: '2', title: 'История Таджикистана: Саманиды', subject: 'История', questionsCount: 15, image: 'https://picsum.photos/seed/history/400/300', description: 'Эпоха Исмоила Сомони и расцвет государства.' },
  { id: '3', title: 'Физика: Законы Ньютона', subject: 'Физика', questionsCount: 10, image: 'https://picsum.photos/seed/physics/400/300', description: 'Основные законы динамики.' },
  { id: '4', title: 'Химия: Таблица Менделеева', subject: 'Химия', questionsCount: 25, image: 'https://picsum.photos/seed/chemistry/400/300', description: 'Периодический закон и свойства элементов.' },
  { id: '5', title: 'Биология: Клетка', subject: 'Биология', questionsCount: 15, image: 'https://picsum.photos/seed/biology/400/300', description: 'Строение и функции растительной и животной клетки.' },
  { id: '6', title: 'География: Рельеф Земли', subject: 'География', questionsCount: 12, image: 'https://picsum.photos/seed/geography/400/300', description: 'Горы, равнины и тектонические плиты.' },
  { id: '7', title: 'Литература: Пушкин А.С.', subject: 'Литература', questionsCount: 20, image: 'https://picsum.photos/seed/literature/400/300', description: 'Жизнь и творчество великого поэта.' },
  { id: '8', title: 'Информатика: Алгоритмы', subject: 'Информатика', questionsCount: 10, image: 'https://picsum.photos/seed/it/400/300', description: 'Основы логики и построение блок-схем.' },
  { id: '9', title: 'Английский: Tenses', subject: 'Английский язык', questionsCount: 30, image: 'https://picsum.photos/seed/english/400/300', description: 'Present, Past and Future Simple/Continuous.' },
  { id: '10', title: 'Таджикский язык: Исм', subject: 'Таджикский язык', questionsCount: 15, image: 'https://picsum.photos/seed/tajik/400/300', description: 'Категорияҳои грамматикии исм.' },
  { id: '11', title: 'Геометрия: Теорема Пифагора', subject: 'Математика', questionsCount: 10, image: 'https://picsum.photos/seed/geometry/400/300', description: 'Применение теоремы в прямоугольных треугольниках.' },
  { id: '12', title: 'Астрономия: Солнечная система', subject: 'Астрономия', questionsCount: 20, image: 'https://picsum.photos/seed/space/400/300', description: 'Планеты, спутники и астероиды.' },
  { id: '13', title: 'Экология: Глобальное потепление', subject: 'Экология', questionsCount: 15, image: 'https://picsum.photos/seed/nature/400/300', description: 'Причины и последствия изменения климата.' },
  { id: '14', title: 'Право: Конституция РТ', subject: 'Право', questionsCount: 20, image: 'https://picsum.photos/seed/law/400/300', description: 'Основы государственного строя Таджикистана.' },
  { id: '15', title: 'Искусство: Ренессанс', subject: 'Искусство', questionsCount: 12, image: 'https://picsum.photos/seed/art/400/300', description: 'Великие художники эпохи Возрождения.' },
  { id: '16', title: 'Экономика: Спрос и предложение', subject: 'Экономика', questionsCount: 15, image: 'https://picsum.photos/seed/money/400/300', description: 'Рыночные механизмы и ценообразование.' },
  { id: '17', title: 'Черчение: Проекции', subject: 'Черчение', questionsCount: 10, image: 'https://picsum.photos/seed/drawing/400/300', description: 'Построение видов и разрезов.' },
  { id: '18', title: 'Музыка: Классицизм', subject: 'Музыка', questionsCount: 12, image: 'https://picsum.photos/seed/music/400/300', description: 'Моцарт, Бетховен, Гайдн.' },
  { id: '19', title: 'Технология: Обработка дерева', subject: 'Технология', questionsCount: 10, image: 'https://picsum.photos/seed/wood/400/300', description: 'Инструменты и техника безопасности.' },
  { id: '20', title: 'Психология: Типы темперамента', subject: 'Психология', questionsCount: 15, image: 'https://picsum.photos/seed/mind/400/300', description: 'Сангвиник, холерик, флегматик, меланхолик.' },
];

export const MOCK_RESULTS = [
  { id: 'r1', testTitle: 'Алгебра: Квадратные уравнения', score: 18, maxScore: 20, date: '2024-03-25' },
  { id: 'r2', testTitle: 'Физика: Законы Ньютона', score: 9, maxScore: 10, date: '2024-03-26' },
  { id: 'r3', testTitle: 'История Таджикистана: Саманиды', score: 15, maxScore: 15, date: '2024-03-28' },
];

export const MOCK_BOOKS = [
  { id: 'b1', title: 'Алгебра 9 класс', author: 'А. Шарковски', cover: 'https://picsum.photos/seed/book1/200/300', downloadUrl: '#' },
  { id: 'b2', title: 'История Таджикского Народа', author: 'Б. Гафуров', cover: 'https://picsum.photos/seed/book2/200/300', downloadUrl: '#' },
  { id: 'b3', title: 'Физика: Учебник', author: 'Пёрышкин', cover: 'https://picsum.photos/seed/book3/200/300', downloadUrl: '#' },
  { id: 'b4', title: 'Литература: Хрестоматия', author: 'Сборник', cover: 'https://picsum.photos/seed/book4/200/300', downloadUrl: '#' },
  { id: 'b5', title: 'Химия: Основы', author: 'Рудзитис', cover: 'https://picsum.photos/seed/book5/200/300', downloadUrl: '#' },
];
